require('dotenv').config();
require('./src/proto/prototypes').init();
const mongoService = require('./src/svc/db/mongo-service');
const debugService = require('./src/svc/utils/debug-service');
const fastifyService = require('./src/svc/utils/fastify-service');
const mailService = require('./src/svc/mails/mail-service');
const controlService = require('./src/svc/utils/control-service');
const userService = require('./src/svc/apis/user-service');
const paramService = require('./src/svc/apis/param-service');
const dataService = require('./src/svc/apis/data-service');
const adminService = require('./src/svc/apis/admin-service');
const vendorService = require('./src/svc/apis/vendor-service');
const reelService = require('./src/svc/apis/reels-service');
const orderService = require('./src/svc/apis/orders-service');
const notifService = require('./src/svc/apis/notification-service');
const bannerService = require('./src/svc/apis/banners-service');
const streakService = require('./src/svc/apis/streak-service');
const feedbackService = require('./src/svc/apis/feedback-service');
const slideService = require('./src/svc/apis/slides-service');
mongoService.initAsync().then(() => {
    fastifyService.init();
    mailService.init();
    debugService.init(fastifyService.instance(), mongoService);
    paramService.init(fastifyService.instance());
    notifService.init(fastifyService.instance());
    controlService.init(fastifyService.instance());
    userService.init(fastifyService.instance());
    adminService.init(fastifyService.instance());
    vendorService.init(fastifyService.instance());
    dataService.init(fastifyService.instance());
    reelService.init(fastifyService.instance());
    orderService.init(fastifyService.instance());
    bannerService.init(fastifyService.instance());
    feedbackService.init(fastifyService.instance());
    streakService.init(fastifyService.instance());
    slideService.init(fastifyService.instance());
    fastifyService.listenAsync();
});